name: CI

on:
  push:
    branches:
    - master
    - release/*

jobs:
  android-build:
    runs-on: ubuntu-latest

    steps:
    - name: Use coturiv/setup-ionic
      uses: coturiv/setup-ionic@v1
      with:
        cordova-version: 8

    - name: Build
      run: |
        ionic init
        ionic cordova build android --prod
